server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://vdtry_postgres:5434/management
    username: vdtry06
    password: vdtry06

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
